### ISSUE TITLE
Unable to receive message

### ISSUE THREAD

**Issue by ktpktr0** [web-xiaxia/skywalking-webhook-dingding-talk-docker#2]
I use k8s to deploy skywalking 8.0, and use k8s to deploy webhook. Skywalking background can successfully obtain the alarm information, but webhook cannot send the message to Dingding

Skywalking background alarm：
![image](https://user-images.githubusercontent.com/41657218/110414854-b9de4480-80cb-11eb-9ac2-c65ee79d5bf2.png)

Deploying webhook in k8s
```
kind: Deployment
metadata:
  labels:
    app: skywalking-webhook
  name: skywalking-webhook-dingdingtalk
  namespace: skywalking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skywalking-webhook
  template:
    metadata:
      labels:
        app: skywalking-webhook
    spec:
      containers:
      - env:
        - name: TOKEN
          value: "1b30a792c1ee6f687eed961795d0cc0d617263e87c1c25da934615dbc0f5acef"
        name: skywalking-webhook
        image: webxiaxia/skywalking-webhook-dingding-talk:v1.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8082
            name: tcp
            protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: skywalking-webhook
  name: skywalking-webhook-service
  namespace: skywalking
spec:
  ports:
  - name: tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: skywalking-webhook
  sessionAffinity: None
  type: ClusterIP
```

webhook logs :

# kubectl logs -f skywalking-webhook-dingdingtalk-5f8c9597d4-8nlls -n skywalking         
Application starting
